version: "3.9"
services:
  web:
    image: nginx:1.15.5-alpine-perl
    ports:
      - "8000:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  app:
    build: ./vuc-app
    ports:
      - 8080:8080
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.10.0
    environment:
      - SCRAPE_URI=http://web/stub_status
    ports:
      - 9113:9113
    depends_on:
      - web
